# Generated by Django 3.2.8 on 2021-10-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_message', '0002_alter_message_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='EncryptedMessage',
        ),
    ]
